/**
 * modalIndirizziCtrl - controller
 * Controller per la finestra modale di gestioneindirizzi
 *
 */
function modalIndirizziCtrl($scope, $rootScope, $http) {

  $scope.nazioni = [
    { nome: "Afghanistan", code: "AF" },
    { nome: "Åland Islands", code: "AX" },
    { nome: "Albania", code: "AL" },
    { nome: "Algeria", code: "DZ" },
    { nome: "American Samoa", code: "AS" },
    { nome: "Andorra", code: "AD" },
    { nome: "Angola", code: "AO" },
    { nome: "Anguilla", code: "AI" },
    { nome: "Antarctica", code: "AQ" },
    { nome: "Antigua and Barbuda", code: "AG" },
    { nome: "Argentina", code: "AR" },
    { nome: "Armenia", code: "AM" },
    { nome: "Aruba", code: "AW" },
    { nome: "Australia", code: "AU" },
    { nome: "Austria", code: "AT" },
    { nome: "Azerbaijan", code: "AZ" },
    { nome: "Bahamas", code: "BS" },
    { nome: "Bahrain", code: "BH" },
    { nome: "Bangladesh", code: "BD" },
    { nome: "Barbados", code: "BB" },
    { nome: "Belarus", code: "BY" },
    { nome: "Belgium", code: "BE" },
    { nome: "Belize", code: "BZ" },
    { nome: "Benin", code: "BJ" },
    { nome: "Bermuda", code: "BM" },
    { nome: "Bhutan", code: "BT" },
    { nome: "Bolivia", code: "BO" },
    { nome: "Bosnia and Herzegovina", code: "BA" },
    { nome: "Botswana", code: "BW" },
    { nome: "Bouvet Island", code: "BV" },
    { nome: "Brazil", code: "BR" },
    { nome: "British Indian Ocean Territory", code: "IO" },
    { nome: "Brunei Darussalam", code: "BN" },
    { nome: "Bulgaria", code: "BG" },
    { nome: "Burkina Faso", code: "BF" },
    { nome: "Burundi", code: "BI" },
    { nome: "Cambodia", code: "KH" },
    { nome: "Cameroon", code: "CM" },
    { nome: "Canada", code: "CA" },
    { nome: "Cape Verde", code: "CV" },
    { nome: "Cayman Islands", code: "KY" },
    { nome: "Central African Republic", code: "CF" },
    { nome: "Chad", code: "TD" },
    { nome: "Chile", code: "CL" },
    { nome: "China", code: "CN" },
    { nome: "Christmas Island", code: "CX" },
    { nome: "Cocos (Keeling) Islands", code: "CC" },
    { nome: "Colombia", code: "CO" },
    { nome: "Comoros", code: "KM" },
    { nome: "Congo", code: "CG" },
    { nome: "Congo, The Democratic Republic of the", code: "CD" },
    { nome: "Cook Islands", code: "CK" },
    { nome: "Costa Rica", code: "CR" },
    { nome: "Cote D'Ivoire", code: "CI" },
    { nome: "Croatia", code: "HR" },
    { nome: "Cuba", code: "CU" },
    { nome: "Cyprus", code: "CY" },
    { nome: "Czech Republic", code: "CZ" },
    { nome: "Denmark", code: "DK" },
    { nome: "Djibouti", code: "DJ" },
    { nome: "Dominica", code: "DM" },
    { nome: "Dominican Republic", code: "DO" },
    { nome: "Ecuador", code: "EC" },
    { nome: "Egypt", code: "EG" },
    { nome: "El Salvador", code: "SV" },
    { nome: "Equatorial Guinea", code: "GQ" },
    { nome: "Eritrea", code: "ER" },
    { nome: "Estonia", code: "EE" },
    { nome: "Ethiopia", code: "ET" },
    { nome: "Falkland Islands (Malvinas)", code: "FK" },
    { nome: "Faroe Islands", code: "FO" },
    { nome: "Fiji", code: "FJ" },
    { nome: "Finland", code: "FI" },
    { nome: "France", code: "FR" },
    { nome: "French Guiana", code: "GF" },
    { nome: "French Polynesia", code: "PF" },
    { nome: "French Southern Territories", code: "TF" },
    { nome: "Gabon", code: "GA" },
    { nome: "Gambia", code: "GM" },
    { nome: "Georgia", code: "GE" },
    { nome: "Germany", code: "DE" },
    { nome: "Ghana", code: "GH" },
    { nome: "Gibraltar", code: "GI" },
    { nome: "Greece", code: "GR" },
    { nome: "Greenland", code: "GL" },
    { nome: "Grenada", code: "GD" },
    { nome: "Guadeloupe", code: "GP" },
    { nome: "Guam", code: "GU" },
    { nome: "Guatemala", code: "GT" },
    { nome: "Guernsey", code: "GG" },
    { nome: "Guinea", code: "GN" },
    { nome: "Guinea-Bissau", code: "GW" },
    { nome: "Guyana", code: "GY" },
    { nome: "Haiti", code: "HT" },
    { nome: "Heard Island and Mcdonald Islands", code: "HM" },
    { nome: "Holy See (Vatican City State)", code: "VA" },
    { nome: "Honduras", code: "HN" },
    { nome: "Hong Kong", code: "HK" },
    { nome: "Hungary", code: "HU" },
    { nome: "Iceland", code: "IS" },
    { nome: "India", code: "IN" },
    { nome: "Indonesia", code: "ID" },
    { nome: "Iran, Islamic Republic Of", code: "IR" },
    { nome: "Iraq", code: "IQ" },
    { nome: "Ireland", code: "IE" },
    { nome: "Isle of Man", code: "IM" },
    { nome: "Israel", code: "IL" },
    { nome: "Italy", code: "IT" },
    { nome: "Jamaica", code: "JM" },
    { nome: "Japan", code: "JP" },
    { nome: "Jersey", code: "JE" },
    { nome: "Jordan", code: "JO" },
    { nome: "Kazakhstan", code: "KZ" },
    { nome: "Kenya", code: "KE" },
    { nome: "Kiribati", code: "KI" },
    { nome: "Korea, Democratic People's Republic of", code: "KP" },
    { nome: "Korea, Republic of", code: "KR" },
    { nome: "Kuwait", code: "KW" },
    { nome: "Kyrgyzstan", code: "KG" },
    { nome: "Lao People's Democratic Republic", code: "LA" },
    { nome: "Latvia", code: "LV" },
    { nome: "Lebanon", code: "LB" },
    { nome: "Lesotho", code: "LS" },
    { nome: "Liberia", code: "LR" },
    { nome: "Libyan Arab Jamahiriya", code: "LY" },
    { nome: "Liechtenstein", code: "LI" },
    { nome: "Lithuania", code: "LT" },
    { nome: "Luxembourg", code: "LU" },
    { nome: "Macao", code: "MO" },
    { nome: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
    { nome: "Madagascar", code: "MG" },
    { nome: "Malawi", code: "MW" },
    { nome: "Malaysia", code: "MY" },
    { nome: "Maldives", code: "MV" },
    { nome: "Mali", code: "ML" },
    { nome: "Malta", code: "MT" },
    { nome: "Marshall Islands", code: "MH" },
    { nome: "Martinique", code: "MQ" },
    { nome: "Mauritania", code: "MR" },
    { nome: "Mauritius", code: "MU" },
    { nome: "Mayotte", code: "YT" },
    { nome: "Mexico", code: "MX" },
    { nome: "Micronesia, Federated States of", code: "FM" },
    { nome: "Moldova, Republic of", code: "MD" },
    { nome: "Monaco", code: "MC" },
    { nome: "Mongolia", code: "MN" },
    { nome: "Montserrat", code: "MS" },
    { nome: "Morocco", code: "MA" },
    { nome: "Mozambique", code: "MZ" },
    { nome: "Myanmar", code: "MM" },
    { nome: "Namibia", code: "NA" },
    { nome: "Nauru", code: "NR" },
    { nome: "Nepal", code: "NP" },
    { nome: "Netherlands", code: "NL" },
    { nome: "Netherlands Antilles", code: "AN" },
    { nome: "New Caledonia", code: "NC" },
    { nome: "New Zealand", code: "NZ" },
    { nome: "Nicaragua", code: "NI" },
    { nome: "Niger", code: "NE" },
    { nome: "Nigeria", code: "NG" },
    { nome: "Niue", code: "NU" },
    { nome: "Norfolk Island", code: "NF" },
    { nome: "Northern Mariana Islands", code: "MP" },
    { nome: "Norway", code: "NO" },
    { nome: "Oman", code: "OM" },
    { nome: "Pakistan", code: "PK" },
    { nome: "Palau", code: "PW" },
    { nome: "Palestinian Territory, Occupied", code: "PS" },
    { nome: "Panama", code: "PA" },
    { nome: "Papua New Guinea", code: "PG" },
    { nome: "Paraguay", code: "PY" },
    { nome: "Peru", code: "PE" },
    { nome: "Philippines", code: "PH" },
    { nome: "Pitcairn", code: "PN" },
    { nome: "Poland", code: "PL" },
    { nome: "Portugal", code: "PT" },
    { nome: "Puerto Rico", code: "PR" },
    { nome: "Qatar", code: "QA" },
    { nome: "Reunion", code: "RE" },
    { nome: "Romania", code: "RO" },
    { nome: "Russian Federation", code: "RU" },
    { nome: "Rwanda", code: "RW" },
    { nome: "Saint Helena", code: "SH" },
    { nome: "Saint Kitts and Nevis", code: "KN" },
    { nome: "Saint Lucia", code: "LC" },
    { nome: "Saint Pierre and Miquelon", code: "PM" },
    { nome: "Saint Vincent and the Grenadines", code: "VC" },
    { nome: "Samoa", code: "WS" },
    { nome: "San Marino", code: "SM" },
    { nome: "Sao Tome and Principe", code: "ST" },
    { nome: "Saudi Arabia", code: "SA" },
    { nome: "Senegal", code: "SN" },
    { nome: "Serbia and Montenegro", code: "CS" },
    { nome: "Seychelles", code: "SC" },
    { nome: "Sierra Leone", code: "SL" },
    { nome: "Singapore", code: "SG" },
    { nome: "Slovakia", code: "SK" },
    { nome: "Slovenia", code: "SI" },
    { nome: "Solomon Islands", code: "SB" },
    { nome: "Somalia", code: "SO" },
    { nome: "South Africa", code: "ZA" },
    { nome: "South Georgia and the South Sandwich Islands", code: "GS" },
    { nome: "Spain", code: "ES" },
    { nome: "Sri Lanka", code: "LK" },
    { nome: "Sudan", code: "SD" },
    { nome: "Surinome", code: "SR" },
    { nome: "Svalbard and Jan Mayen", code: "SJ" },
    { nome: "Swaziland", code: "SZ" },
    { nome: "Sweden", code: "SE" },
    { nome: "Switzerland", code: "CH" },
    { nome: "Syrian Arab Republic", code: "SY" },
    { nome: "Taiwan, Province of China", code: "TW" },
    { nome: "Tajikistan", code: "TJ" },
    { nome: "Tanzania, United Republic of", code: "TZ" },
    { nome: "Thailand", code: "TH" },
    { nome: "Timor-Leste", code: "TL" },
    { nome: "Togo", code: "TG" },
    { nome: "Tokelau", code: "TK" },
    { nome: "Tonga", code: "TO" },
    { nome: "Trinidad and Tobago", code: "TT" },
    { nome: "Tunisia", code: "TN" },
    { nome: "Turkey", code: "TR" },
    { nome: "Turkmenistan", code: "TM" },
    { nome: "Turks and Caicos Islands", code: "TC" },
    { nome: "Tuvalu", code: "TV" },
    { nome: "Uganda", code: "UG" },
    { nome: "Ukraine", code: "UA" },
    { nome: "United Arab Emirates", code: "AE" },
    { nome: "United Kingdom", code: "GB" },
    { nome: "United States", code: "US" },
    { nome: "United States Minor Outlying Islands", code: "UM" },
    { nome: "Uruguay", code: "UY" },
    { nome: "Uzbekistan", code: "UZ" },
    { nome: "Vanuatu", code: "VU" },
    { nome: "Venezuela", code: "VE" },
    { nome: "Vietnam", code: "VN" },
    { nome: "Virgin Islands, British", code: "VG" },
    { nome: "Virgin Islands, U.S.", code: "VI" },
    { nome: "Wallis and Futuna", code: "WF" },
    { nome: "Western Sahara", code: "EH" },
    { nome: "Yemen", code: "YE" },
    { nome: "Zambia", code: "ZM" },
    { nome: "Zimbabwe", code: "ZW" }
  ];


  $scope.comuni = [
    { nome: "gdkqhgkjqw", code: "AF" },
    { nome: "wefewfefw1", code: "AF" },
    { nome: "Comune ccccccc1", code: "AF" },
    { nome: "Comune dddddd1", code: "AF" },
    { nome: "Comune eeeeee1", code: "AF" },
    { nome: "Comune fffffff1", code: "AF" },
    { nome: "eklfàlòkwàlfkComune 1", code: "AF" },
    { nome: "Comune eee1", code: "AF" },
    { nome: "Comuneee 1", code: "AF" },
    { nome: "Comune eee1", code: "AF" },
    { nome: "Comeeeeune 1", code: "AF" },
    { nome: "Comuneeeee 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },
    { nome: "Comune 1", code: "AF" },

  ];

  $scope.frazioni = [
    { nome: "Frazione gdkqhgkjqw", code: "AF" },
    { nome: "Frazione wefewfefw1", code: "AF" },
    { nome: "Frazione ccccccc1", code: "AF" },
    { nome: "ddddd d1", code: "AF" },
    { nome: "eeee ee1", code: "AF" },
    { nome: "ffff fff1", code: "AF" },
    { nome: "eklfàl òkwàlfk Comune 1", code: "AF" },
    { nome: "Frazione eee1", code: "AF" },
    { nome: "Frazione 1", code: "AF" },
    { nome: "Frazione tal dei tali eee1", code: "AF" },
    { nome: "Frazione tal dei tali", code: "AF" },
    { nome: "Frazione  aa a a a e rrrr eeeee 1", code: "AF" },
  ];

  $scope.vie = [
    { nome: "Via gdkqhgkjqw", code: "AF" },
    { nome: "Via wefewfefw1", code: "AF" },
    { nome: "Via  ccccccc1", code: "AF" },
    { nome: "ddddd d1", code: "AF" },
    { nome: "eeee ee1", code: "AF" },
    { nome: "ffff fff1", code: "AF" },
    { nome: "eklfàl òkwàlfk Via 1", code: "AF" },
    { nome: "Piazza  eee1", code: "AF" },
    { nome: "Viale 1", code: "AF" },
    { nome: "Via tal dei tali eee1", code: "AF" },
    { nome: "Via tal dei tali", code: "AF" },
    { nome: "Via  aa a a a e rrrr eeeee 1", code: "AF" },
  ];



  $scope.Tmp = {
    IndirizzoCodificato: {
      Nazione: "",
      Comune: "",
      Cap: "",
      Frazione: "",
      Via: ""
    },
    IndirizzoNonCodificato: {
      Localita: "",
      Cap: "",
      Maso: "",
      Via: "",
      IndirizzoCompleto: ""
    }
  };

  $scope.usaIndirizzo = function() {
    var xxx = $rootScope.datiAssistito.Indirizzi.find(item => {
      return item.UsaIndirizzo === "Si";
    });
    debugger;
    if (xxx) {
      $scope.Tmp.IndirizzoCodificato.Nazione = xxx.Nazione;
      $scope.Tmp.IndirizzoCodificato.Comune = xxx.Comune;
      $scope.Tmp.IndirizzoCodificato.Cap = xxx.Cap;
      $scope.Tmp.IndirizzoCodificato.Frazione = xxx.Frazione;
      $scope.Tmp.IndirizzoCodificato.Via = xxx.Via;

      $scope.Tmp.IndirizzoNonCodificato.Localita = xxx.Comune;
      $scope.Tmp.IndirizzoNonCodificato.Cap = xxx.Cap;
      $scope.Tmp.IndirizzoNonCodificato.Maso = "";
      $scope.Tmp.IndirizzoNonCodificato.Via = xxx.Via;
      $scope.Tmp.IndirizzoNonCodificato.IndirizzoCompleto =
        xxx.Via + " " + xxx.Comune + " " + xxx.Cap + " " + xxx.Nazione;

      $scope.Tmp.NroCivico = xxx.Civico;

      swal(
        "Indirizzo correttamente copiato! Per verificare osservare il Cap dell'indirizzo codificato e l'indirizzo completo del non codifcato. Non viene copiato correttamente perche solo i valori delle options sono ammessi nelle select! "
      );
    }
  };
}
